source 'https://rubygems.org'

gem 'middleman'

 group :development do
   gem 'middleman-livereload', '~>3.4.3'
   gem 'rubocop', require: false
   gem 'rubocop-rspec'
 end

 group :testing do
   gem 'rspec', '~>3.4.0'
 end

 gem 'byebug', '~>8.2.0', group: [:development, :testing]
